# uas-project/docker-compose.yml
# File ini mendefinisikan dan menjalankan aplikasi multi-kontainer Docker Anda.

# Hapus baris version: '3.8' karena sudah usang
# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Asumsikan Anda memiliki Dockerfile untuk aplikasi web
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
      # >>> PASTIKAN BARIS INI ADA DAN TEPAT DI SINI <<<
      DATABASE_HOST: db # Kontainer web harus terhubung ke service 'db' di jaringan Docker
      DATABASE_PORT: 5432 # Port default PostgreSQL
    env_file:
      - ./.env # Ini untuk variabel lain seperti kredensial DB (POSTGRES_USER, POSTGRES_PASSWORD)
    volumes:
      # Bind mount: Menyinkronkan folder 'app' lokal Anda dengan /app di dalam kontainer.
      # Ini akan mencakup sub-folder 'src', 'templates', dan 'static'.
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network
    command: python src/app.py # Memberi tahu kontainer untuk menjalankan app.py dari folder src


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
